name: Run script to see what happens

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  execute:
    # Ubuntu is the closest thing available to Pop!_OS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run the script
        run: |
          ./src/install-all.sh
